name: "Ship Kubernetes Logs to OpenObserve"
description: "Use Vector to send Kubernetes Logs to OpenObserve"
author: "FNNDSC"
inputs:
  kind_config:
    description: 'Path to KinD config file'
    required: false
    default: ''
  openobserve_endpoint:
    description: 'OpenObserve organization API endpoint e.g. https://api.openobserve.ai/api/default/'
    required: true
  openobserve_username:
    description: 'Your OpenObserve username'
    required: true
  openobserve_password:
    description: 'Key/Password for your OpenObserve username (must not contain ")'
    required: true
  openobserve_stream:
    description: 'Name of log stream'
    required: false
    default: ''
  namespace:
    description: 'Kubernetes namespace where to install Vector'
    required: false
    default: 'monitoring'
  wait_until_ready:
    description: 'Wait until Vector is ready'
    required: false
    default: ''
  scrape_interval_secs:
    description: 'Interval between scrapes of /metrics/cadvisor'
    required: false
    default: ''

branding:
  color: "orange"
  icon: "align-left"

runs:
  using: node20
  main: main.js
  post: post.js
